Добавлена поддержка httpx
gpncr-repos/PythonProjectTemplates pull request #10
Opened 2024-09-23 14:07 UTC by vladushka2000

2024-10-14 16:43 UTC, Dementiy commented on {{ cookiecutter.service_name }}/src/repositories/http_repository.py
> +class SyncHTTPRepository(base_repository.BaseRepository):
question: А в каких случаях/задачах нужен репозиторий для http-запросов? Пока могу представить пример использования только когда есть достаточно простой CRUD-сервис. И я не совсем понимаю какую роль могут играть commit/rollback в таком случае.

2024-10-14 16:43 UTC, Dementiy commented on {{ cookiecutter.service_name }}/src/interfaces/base_http_session_maker.py
> +        self._client = httpx.Client()
suggestion: Думаю надо таймауты добавить

2025-04-03 09:20 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/repositories/http_connection_proxy.py
> +class HTTPSyncSession(base_proxy.ConnectionProxy):
pick: пересмотри

2025-04-03 09:22 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/tools/di_containers/http_integration_di_container.py
> +class HTTPSyncIntegrationContainer(containers.DeclarativeContainer):
pick: убедиться, что надо именно так с учетом прошлого коммента

2025-04-03 09:23 UTC, Rognak requested changes
проверь

2025-04-04 17:32 UTC, vladushka2000 commented on {{ cookiecutter.service_name }}/src/tools/di_containers/http_integration_di_container.py
> +class HTTPSyncIntegrationContainer(containers.DeclarativeContainer):
сделал правочки

2025-04-04 17:32 UTC, merged