Добавлена поддержка работы с БД через psycopg
gpncr-repos/PythonProjectTemplates pull request #17
Opened 2024-11-02 10:59 UTC by PvtJoker91

2024-11-05 16:38 UTC, PvtJoker91 commented on {{ cookiecutter.service_name }}/src/storage/psycopg/psycopg_connection.py
> +class PsycopgSyncConnection:
нужно подумать как связать эти подключения через общий интерфейс. ConnectionProxy пока не вижу как тут использовать

2024-11-05 16:39 UTC, PvtJoker91 commented on {{ cookiecutter.service_name }}/src/tools/di_containers/postgres_container.py
> +    wiring_config = containers.WiringConfiguration(packages=["web.entrypoints"])
поправил. Оставлял для тестирования работоспособности

2024-11-05 16:39 UTC, PvtJoker91 commented on {{ cookiecutter.service_name }}/src/repositories/sql_tools.py
> +    Сформировать sql строку для создания записи в таблицу
добавил

2024-11-05 16:41 UTC, PvtJoker91 commented on {{ cookiecutter.service_name }}/src/repositories/psycopg_repository.py
> +    def create(self, table: str, data: dict[str, Any]) -> None:
добавил

2024-11-05 16:42 UTC, PvtJoker91 commented on {{ cookiecutter.service_name }}/src/repositories/psycopg_repository.py
> +
настроил precommit

2024-11-05 16:42 UTC, PvtJoker91 commented on {{ cookiecutter.service_name }}/src/repositories/sql_tools.py
> +# thirdparty
сделал

2024-11-05 16:43 UTC, PvtJoker91 commented on {{ cookiecutter.service_name }}/src/repositories/psycopg_repository.py
> +            with conn.cursor() as cursor:
server-side курсор не реализовывал. Показалось как-то сложно) Не нашел реализации в дарсе

2024-11-06 09:45 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/repositories/psycopg_repository.py
> +        with self._connection.get_connection() as conn:
Он получается так будет на каждый вызов открываться соединение, либо брать из пула... Похоже здесь UOW действительно поможет

2024-11-06 09:47 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/repositories/psycopg_repository.py
> +            with conn.cursor() as cursor:
Давайте посмотрим в сторону server-side курсор, либо возможности выбора конкретного типа курсора

2024-11-06 09:51 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/interfaces/base_raw_sql_creator.py
> +        ...
pick: Предлагаю для единообразия писать через raise

2024-11-26 10:15 UTC, vladushka2000 commented
После правок необходимо еще раз протестировать

2024-11-26 10:16 UTC, vladushka2000 commented
Устранить конфликты

2024-11-26 10:16 UTC, vladushka2000 commented
Устранить конфликты

2024-12-04 13:17 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/repositories/asyncpg_repository.py
> +class AsyncpgRepository(base_repository.BaseRepository):
thought: возможно, что для raw-sql и не нужен базовый репозиторий

В самом деле, а для чего? Здесь можно вполне обойтись абстракциями. К тому же, есть соблазн в update засунуть insert. Просто потому что могу.

2024-12-04 13:19 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/repositories/tools/sql_tools.py
> +class PsycopgRawSQLCreator(BaseRawSQLCreator):
question: Насколько я помню, мы договаривались пока не включать Creator.

2024-12-04 13:22 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/storage/raw_postgres/asyncpg_cursor_proxies.py
> +            if row_number == rows_count:
question: разве rows_count как ограничение не стоит уже в строках 62 и 64?

2024-12-06 06:03 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/tools/di_containers/raw_postgres_container.py
> +    )
pick: добавить комментарий типа

```python
# добавьте ваши uow и repos сюда
```

2024-12-06 06:16 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/config/redis_config.py
> +redis_config = RedisConfig()
question: что здесь Redis делает? Oo

2024-12-06 06:18 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/storage/raw_postgres/psycopg_cursor_proxies.py
> +from typing import Iterable
pick: предлагаю закинуть в пакет

2024-12-06 06:20 UTC, Rognak commented on {{ cookiecutter.service_name }}/src/testik.py
> +import asyncio
pick: Закинуть в usage example

2024-12-06 06:22 UTC, Rognak requested changes
thought: Давай в RoadMap добавим research на psocopg async

2024-12-13 06:22 UTC, Rognak approved these changes

2024-12-13 06:47 UTC, merged